# Site settings
title: Neşe Rüzgarı 
description: Bir Blog Denemesi
url: https://neseruzgari.github.io
baseurl: "" # The subpath of your site, e.g., /blog. If not, leave as empty string.

# Theme settings
#theme: jekyll-theme-time-machine
theme: jekyll-theme-merlot # Change this to the theme you want

# Build settings
markdown: kramdown
highlighter: rouge

github:
  is_project_page: false
show_github_banner: false
